a = input (' what is your first name? ')
b = input (' what is your favorite word? ')
print (' hello ', a, ' the', b,'!')
print (' now you can make random nicknames. ')
c = input (' what is your freinds name? ')
d = input (' what is a word about your freind? ')
print (' your freinds nickname is now',c,'the',d)
input (' what is your favorite nickname? ')
print (' we appreciate your oppinion')
